name: multi event CI/CD

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  multi_event_job: # Changed from multi-eventJob
    runs-on: ubuntu-latest
    steps:
      - name: "Echo Github Ref"
      - run: echo "REF: t"